//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProfileFillingTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public string initialBaudRateValue {
            get {
                return ((string)(this["initialBaudRateValue"]));
            }
            set {
                this["initialBaudRateValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string initialPasswordValue {
            get {
                return ((string)(this["initialPasswordValue"]));
            }
            set {
                this["initialPasswordValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password")]
        public string initialEncryptionModeValue {
            get {
                return ((string)(this["initialEncryptionModeValue"]));
            }
            set {
                this["initialEncryptionModeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00112233445566778899AABBCCDDEEFF")]
        public string initialEncryptionKeyValue {
            get {
                return ((string)(this["initialEncryptionKeyValue"]));
            }
            set {
                this["initialEncryptionKeyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00112233445566778899AABBCCDDEEFF")]
        public string initialAuthenticationKeyValue {
            get {
                return ((string)(this["initialAuthenticationKeyValue"]));
            }
            set {
                this["initialAuthenticationKeyValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1 - Management")]
        public string initialUseAssociationValue {
            get {
                return ((string)(this["initialUseAssociationValue"]));
            }
            set {
                this["initialUseAssociationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool initial1107UseValue {
            get {
                return ((bool)(this["initial1107UseValue"]));
            }
            set {
                this["initial1107UseValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool radioButtonIpSelected {
            get {
                return ((bool)(this["radioButtonIpSelected"]));
            }
            set {
                this["radioButtonIpSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string initialComPortValue {
            get {
                return ((string)(this["initialComPortValue"]));
            }
            set {
                this["initialComPortValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool radioButtonBaudRateSelected {
            get {
                return ((bool)(this["radioButtonBaudRateSelected"]));
            }
            set {
                this["radioButtonBaudRateSelected"] = value;
            }
        }
    }
}
